import { useMemo, useState } from "react";
import { Archive, BarChart3, CircleDollarSign, ClipboardList, Download, Package, Printer, ReceiptText, ShoppingCart, Settings2, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const money = (value: number) => `KES ${value.toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const csvCell = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;
type Section = "dashboard" | "fees" | "received" | "spent" | "procurement" | "stores" | "assets" | "maintenance" | "reports" | "audit";
const sections: Array<[Section, string, typeof WalletCards]> = [["dashboard", "Dashboard", BarChart3], ["fees", "Fees", WalletCards], ["received", "Money received", CircleDollarSign], ["spent", "Money spent", ReceiptText], ["procurement", "Procurement", ShoppingCart], ["stores", "Stores", Package], ["assets", "Assets", Archive], ["maintenance", "Maintenance", Settings2], ["reports", "Reports", BarChart3], ["audit", "Audit trail", ClipboardList]];

export function FinanceWorkspace() {
  const overview = trpc.smis.finance.overview.useQuery({});
  const summary = trpc.smis.finance.summary.useQuery();
  const expenditures = trpc.smis.finance.expenditures.useQuery();
  const store = trpc.smis.store.overview.useQuery();
  const learners = trpc.smis.learners.list.useQuery({});
  const utils = trpc.useUtils();
  const [section, setSection] = useState<Section>("dashboard");
  const [learnerId, setLearnerId] = useState("");
  const [amount, setAmount] = useState("");
  const [method, setMethod] = useState<"mpesa" | "bank" | "cash">("mpesa");
  const [reference, setReference] = useState("");
  const [spendAmount, setSpendAmount] = useState("");
  const [spendCategory, setSpendCategory] = useState("Procurement");
  const [spendDescription, setSpendDescription] = useState("");
  const [responsiblePerson, setResponsiblePerson] = useState("");
  const payment = trpc.smis.finance.recordPayment.useMutation({ onSuccess: () => { toast.success("Money received recorded"); setAmount(""); setReference(""); void utils.smis.finance.invalidate(); }, onError: error => toast.error(error.message.replaceAll("_", " ")) });
  const expenditure = trpc.smis.finance.recordExpenditure.useMutation({ onSuccess: () => { toast.success("Money spent recorded"); setSpendAmount(""); setSpendDescription(""); setResponsiblePerson(""); void utils.smis.finance.invalidate(); }, onError: error => toast.error(error.message.replaceAll("_", " ")) });
  const balances = overview.data?.balances ?? [];
  const lowStock = (store.data ?? []).filter(item => item.reorderLevel > 0 && item.quantity <= item.reorderLevel);
  const totalReceived = summary.data?.collected ?? overview.data?.totals.paid ?? 0;
  const totalSpent = summary.data?.expenditure ?? 0;
  const topBalances = useMemo(() => [...balances].sort((a, b) => b.balance - a.balance).slice(0, 10), [balances]);
  const exportLedger = () => { const rows = [["Learner", "Admission No.", "Required", "Paid", "Balance"], ...balances.map(row => [row.learner.fullName, row.learner.admissionNumber, row.required, row.paid, row.balance])]; const url = URL.createObjectURL(new Blob([rows.map(row => row.map(csvCell).join(",")).join("\n")], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "nexus-finance-ledger.csv"; link.click(); URL.revokeObjectURL(url); };
  const submitPayment = (event: React.FormEvent) => { event.preventDefault(); if (!learnerId || !amount || !reference.trim()) { toast.error("Select a learner and provide amount and receipt/reference"); return; } payment.mutate({ learnerId: Number(learnerId), amount: Number(amount), paymentMethod: method, reference: reference.trim() }); };
  const submitExpenditure = (event: React.FormEvent) => { event.preventDefault(); if (!spendAmount || !spendDescription.trim() || !responsiblePerson.trim()) { toast.error("Provide amount, description and responsible person"); return; } expenditure.mutate({ expenditureDate: new Date().toISOString().slice(0, 10), amount: Number(spendAmount), category: spendCategory, description: spendDescription.trim(), responsiblePerson: responsiblePerson.trim() }); };
  return <div className="page-enter space-y-6">
    <section className="flex flex-col gap-4 border-b border-[#dfdbd1] pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">Finance & resources · integrated ledger</p><h1 className="mt-1 font-editorial text-[2rem] leading-none text-[#193d32]">Complete school finance workspace.</h1><p className="mt-2 text-sm text-[#69796f]">Fees, money received, money spent, procurement, stores, assets and reports are organized in one accountable workspace.</p></div><div className="flex gap-2"><button onClick={exportLedger} className="quiet-button"><Download size={15}/>Download ledger</button><button onClick={() => window.print()} className="action-button"><Printer size={15}/>Print / PDF</button></div></section>
    <nav className="grid grid-cols-2 gap-2 rounded-xl border border-[#d8ded7] bg-[#fffefa] p-2 sm:grid-cols-4 lg:grid-cols-7" aria-label="Finance sections">{sections.map(([key, label, Icon]) => <button key={key} type="button" onClick={() => setSection(key)} className={`flex items-center justify-center gap-2 rounded-lg px-2 py-3 text-xs font-bold transition ${section === key ? "bg-[#1d6a57] text-white shadow-sm" : "text-[#53675d] hover:bg-[#edf2ed]"}`}><Icon size={15}/>{label}</button>)}</nav>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Fees required" value={money(overview.data?.totals.required ?? 0)} icon={WalletCards}/><Metric label="Money received" value={money(totalReceived)} icon={CircleDollarSign}/><Metric label="Money spent" value={money(totalSpent)} icon={ReceiptText}/><Metric label="Store alerts" value={String(lowStock.length)} icon={Package}/></section>
    {section === "dashboard" && <FinanceDashboard balances={balances} totalReceived={totalReceived} totalSpent={totalSpent} lowStock={lowStock.length} onSection={setSection}/>}
    {section === "fees" && <FeesSection balances={topBalances} money={money} />}
    {section === "received" && <section className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><PaymentForm learners={learners.data ?? []} learnerId={learnerId} setLearnerId={setLearnerId} amount={amount} setAmount={setAmount} method={method} setMethod={setMethod} reference={reference} setReference={setReference} onSubmit={submitPayment} pending={payment.isPending}/><LedgerTable payments={overview.data?.payments ?? []} money={money}/></section>}
    {section === "spent" && <section className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><ExpenditureForm amount={spendAmount} setAmount={setSpendAmount} category={spendCategory} setCategory={setSpendCategory} description={spendDescription} setDescription={setSpendDescription} responsible={responsiblePerson} setResponsible={setResponsiblePerson} onSubmit={submitExpenditure} pending={expenditure.isPending}/><ExpenditureList rows={expenditures.data ?? []} money={money}/></section>}
    {section === "procurement" && <section className="grid gap-6 xl:grid-cols-[1fr_1fr]"><article className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Procurement register</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Purchases and supplier spend</h2><p className="mt-2 text-sm leading-6 text-[#718077]">Record every procurement transaction under Money spent with category <b>Procurement</b>. This keeps supplier purchases, descriptions, responsible officers and dates in the authoritative expenditure ledger.</p><button onClick={() => setSection("spent")} className="action-button mt-5"><ShoppingCart size={15}/>Record procurement spend</button></article><ExpenditureList rows={(expenditures.data ?? []).filter(row => row.category.toLowerCase().includes("procure"))} money={money}/></section>}
    {section === "stores" && <StoreSection items={store.data ?? []} lowStock={lowStock}/>}
    {section === "assets" && <section className="grid gap-4 sm:grid-cols-2"><article className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Asset register</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">School resources and equipment</h2><p className="mt-2 text-sm leading-6 text-[#718077]">Store items and their movement history remain the single operational register for school resources. Use Stores to track receipts, issues and adjustments; procurement spend remains linked through the expenditure trail.</p><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="Tracked resources" value={String(store.data?.length ?? 0)} icon={Archive}/><Metric label="Needs attention" value={String(lowStock.length)} icon={Package}/></div></article><StoreSection items={store.data ?? []} lowStock={lowStock}/></section>}
    {section === "maintenance" && <MaintenanceSection expenditures={expenditures.data ?? []}/>}
    {section === "audit" && <AuditSection/>}
    {section === "reports" && <ReportsSection balances={balances} totalReceived={totalReceived} totalSpent={totalSpent} lowStock={lowStock.length} money={money}/>}
  </div>;
}
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof CircleDollarSign }) { return <article className="soft-card rounded-[1.1rem] p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#637067]">{label}</span><span className="rounded-lg bg-[#e5f1e8] p-2 text-[#1d6a57]"><Icon size={16}/></span></div><p className="mt-5 text-xl font-bold text-[#19342e]">{value}</p></article>; }
function FeesSection({ balances, money }: { balances: Array<any>; money: (v: number) => string }) { return <section className="soft-card overflow-hidden rounded-[1.15rem]"><div className="border-b border-[#e7e2d7] p-5"><p className="eyebrow">Fees management</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Fee balances by learner</h2><p className="mt-1 text-xs text-[#718077]">Required fees come from grade-linked fee structures; payments come from the central receipts ledger.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-[#edf2ed] text-[.62rem] uppercase tracking-wider text-[#53675d]"><tr><th className="p-3">Learner</th><th className="p-3">Admission No.</th><th className="p-3">Required</th><th className="p-3">Paid</th><th className="p-3">Balance</th></tr></thead><tbody>{balances.map(row => <tr key={row.learner.id} className="border-t border-[#eee9df]"><td className="p-3 font-bold text-[#28483f]">{row.learner.fullName}</td><td className="p-3">{row.learner.admissionNumber}</td><td className="p-3">{money(row.required)}</td><td className="p-3 text-[#1d6a57]">{money(row.paid)}</td><td className={`p-3 font-bold ${row.balance > 0 ? "text-[#9c4038]" : "text-[#1d6a57]"}`}>{money(row.balance)}</td></tr>)}</tbody></table>{!balances.length && <p className="p-8 text-center text-sm text-[#718077]">No learner fee records are currently available.</p>}</div></section>; }
function PaymentForm({ learners, learnerId, setLearnerId, amount, setAmount, method, setMethod, reference, setReference, onSubmit, pending }: any) { return <form onSubmit={onSubmit} className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Money received</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Post a learner receipt</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-[#53675d] sm:col-span-2">Learner<select value={learnerId} onChange={e => setLearnerId(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"><option value="">Select learner</option>{learners.map((row: any) => <option key={row.id} value={row.id}>{row.fullName} · {row.admissionNumber}</option>)}</select></label><label className="text-xs font-bold text-[#53675d]">Amount (KES)<input type="number" min="1" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"/></label><label className="text-xs font-bold text-[#53675d]">Method<select value={method} onChange={e => setMethod(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"><option value="mpesa">M-Pesa</option><option value="bank">Bank</option><option value="cash">Cash</option></select></label><label className="text-xs font-bold text-[#53675d] sm:col-span-2">Receipt / transaction reference<input value={reference} onChange={e => setReference(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5" placeholder="e.g. QWE12345"/></label></div><button disabled={pending} className="action-button mt-5">{pending ? "Posting…" : "Post money received"}</button></form>; }
function LedgerTable({ payments, money }: any) { return <article className="soft-card overflow-hidden rounded-[1.15rem]"><div className="border-b border-[#e7e2d7] p-5"><p className="eyebrow">Receipt ledger</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Recent money received</h2></div><div className="divide-y divide-[#eee9df]">{payments.slice(0, 12).map((row: any) => <div key={row.id} className="flex items-center justify-between gap-3 p-4 text-xs"><div><b className="text-[#28483f]">{row.reference}</b><p className="mt-1 text-[#718077]">{row.paymentMethod} · {row.paidAt ? new Date(row.paidAt).toLocaleString("en-KE") : "Recorded"}</p></div><b className="text-[#1d6a57]">{money(Number(row.amount))}</b></div>)}{!payments.length && <p className="p-8 text-sm text-[#718077]">No receipts have been recorded.</p>}</div></article>; }
function ExpenditureForm({ amount, setAmount, category, setCategory, description, setDescription, responsible, setResponsible, onSubmit, pending }: any) { return <form onSubmit={onSubmit} className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Money spent</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Record expenditure or procurement</h2><div className="mt-5 grid gap-3"><label className="text-xs font-bold text-[#53675d]">Amount (KES)<input type="number" min="1" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"/></label><label className="text-xs font-bold text-[#53675d]">Category<select value={category} onChange={e => setCategory(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"><option>Procurement</option><option>Utilities</option><option>Staff welfare</option><option>Maintenance</option><option>Transport</option><option>Other</option></select></label><label className="text-xs font-bold text-[#53675d]">Description<textarea value={description} onChange={e => setDescription(e.target.value)} className="mt-2 min-h-20 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"/></label><label className="text-xs font-bold text-[#53675d]">Responsible officer<input value={responsible} onChange={e => setResponsible(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"/></label></div><button disabled={pending} className="action-button mt-5">{pending ? "Saving…" : "Record money spent"}</button></form>; }
function ExpenditureList({ rows, money }: any) { return <article className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Spend trail</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Recent money spent</h2><div className="mt-4 space-y-2">{rows.slice(0, 12).map((row: any) => <div key={row.id} className="flex items-start justify-between gap-3 rounded-lg border border-[#eee9df] p-3 text-xs"><div><b className="text-[#28483f]">{row.category}</b><p className="mt-1 text-[#718077]">{row.description} · {row.responsiblePerson}</p></div><b className="text-[#9c4038]">{money(Number(row.amount))}</b></div>)}{!rows.length && <p className="text-sm text-[#718077]">No expenditure records have been recorded.</p>}</div></article>; }
function StoreSection({ items, lowStock }: any) { return <section className="grid gap-4 sm:grid-cols-2"><article className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Stores</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Stock and resource control</h2><p className="mt-2 text-sm text-[#718077]">Live quantities are calculated from received, issued and adjustment movements.</p><div className="mt-4 space-y-2">{items.map((item: any) => <div key={item.id} className={`flex items-center justify-between rounded-lg px-3 py-3 text-xs ${lowStock.some((row: any) => row.id === item.id) ? "bg-[#fbf5e5]" : "bg-[#edf2ed]"}`}><span className="font-bold text-[#28483f]">{item.name}</span><span className="font-mono text-[#53675d]">{item.quantity} {item.unit}</span></div>)}{!items.length && <p className="text-sm text-[#718077]">No store items have been configured.</p>}</div></article><article className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Reorder alerts</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Items needing attention</h2><div className="mt-4 space-y-2">{lowStock.map((item: any) => <div key={item.id} className="rounded-lg bg-[#fbf5e5] px-3 py-3 text-xs"><b className="text-[#73551e]">{item.name}</b><p className="mt-1 text-[#9a6c19]">{item.quantity} {item.unit} remaining · reorder at {item.reorderLevel}</p></div>)}{!lowStock.length && <p className="rounded-lg bg-[#e7f0e7] p-3 text-xs text-[#315c4c]">No reorder alerts.</p>}</div></article></section>; }
function ReportsSection({ balances, totalReceived, totalSpent, lowStock, money }: any) { const outstanding = balances.reduce((sum: number, row: any) => sum + row.balance, 0); return <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Fees outstanding" value={money(outstanding)} icon={WalletCards}/><Metric label="Money received" value={money(totalReceived)} icon={CircleDollarSign}/><Metric label="Money spent" value={money(totalSpent)} icon={ReceiptText}/><Metric label="Store alerts" value={String(lowStock)} icon={Package}/><article className="soft-card rounded-[1.15rem] p-5 sm:col-span-2 xl:col-span-4"><p className="eyebrow">Finance reports</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Management summary</h2><div className="mt-5 h-4 overflow-hidden rounded-full bg-[#f2e7cf]"><div className="h-full bg-[#1d6a57]" style={{ width: `${totalReceived + totalSpent ? Math.min(100, Math.round(totalReceived / (totalReceived + totalSpent) * 100)) : 0}%` }}/></div><div className="mt-2 flex justify-between text-xs text-[#718077]"><span>Received versus spent</span><span>{money(totalReceived)} received · {money(totalSpent)} spent</span></div></article></section>; }

function FinanceDashboard({ balances, totalReceived, totalSpent, lowStock, onSection }: any) { const outstanding = balances.reduce((sum: number, row: any) => sum + row.balance, 0); return <section className="space-y-4"><article className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Resources & Finance dashboard</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">School financial command centre</h2><p className="mt-2 text-sm text-[#718077]">Open any workstream below. Totals are calculated from the existing learner, receipt, expenditure and store records.</p></article><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><button onClick={() => onSection("fees")} className="soft-card rounded-[1.1rem] p-4 text-left"><span className="text-xs font-bold text-[#637067]">Fees outstanding</span><p className="mt-3 text-xl font-bold text-[#9c4038]">{money(outstanding)}</p></button><button onClick={() => onSection("received")} className="soft-card rounded-[1.1rem] p-4 text-left"><span className="text-xs font-bold text-[#637067]">Money received</span><p className="mt-3 text-xl font-bold text-[#1d6a57]">{money(totalReceived)}</p></button><button onClick={() => onSection("spent")} className="soft-card rounded-[1.1rem] p-4 text-left"><span className="text-xs font-bold text-[#637067]">Money spent</span><p className="mt-3 text-xl font-bold text-[#9c4038]">{money(totalSpent)}</p></button><button onClick={() => onSection("stores")} className="soft-card rounded-[1.1rem] p-4 text-left"><span className="text-xs font-bold text-[#637067]">Low-stock alerts</span><p className="mt-3 text-xl font-bold text-[#966615]">{lowStock}</p></button></div></section>; }
function MaintenanceSection({ expenditures }: any) { return <section className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Maintenance register</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Maintenance and repair spend</h2><p className="mt-2 text-sm text-[#718077]">Maintenance-related expenditure is shown from the authoritative money-spent ledger.</p><ExpenditureList rows={expenditures.filter((row: any) => row.category.toLowerCase().includes("maint"))} money={money}/></section>; }
function AuditSection() { return <section className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Audit trail</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Finance actions are accountable</h2><p className="mt-3 text-sm leading-6 text-[#53675d]">Receipt posting, expenditure recording, store movements, attendance alerts, and other protected changes are written to the NEXUS audit log. Administrators can review the full audit trail under Administration.</p></section>; }
