import { useMemo, useState } from "react";
import { CircleDollarSign, Download, Package, Printer, ReceiptText, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const money = (value: number) => `KES ${value.toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const csvCell = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export function FinanceWorkspace() {
  const overview = trpc.smis.finance.overview.useQuery({});
  const summary = trpc.smis.finance.summary.useQuery();
  const expenditures = trpc.smis.finance.expenditures.useQuery();
  const store = trpc.smis.store.overview.useQuery();
  const learners = trpc.smis.learners.list.useQuery({});
  const utils = trpc.useUtils();
  const [learnerId, setLearnerId] = useState("");
  const [amount, setAmount] = useState("");
  const [method, setMethod] = useState<"mpesa" | "bank" | "cash">("mpesa");
  const [reference, setReference] = useState("");
  const payment = trpc.smis.finance.recordPayment.useMutation({
    onSuccess: () => { toast.success("Payment recorded in the finance ledger"); setAmount(""); setReference(""); void utils.smis.finance.invalidate(); },
    onError: error => toast.error(error.message.replaceAll("_", " ")),
  });
  const balances = overview.data?.balances ?? [];
  const lowStock = (store.data ?? []).filter(item => item.reorderLevel > 0 && item.quantity <= item.reorderLevel);
  const exportLedger = () => {
    const rows = [["Learner", "Admission No.", "Required", "Paid", "Balance"], ...balances.map(row => [row.learner.fullName, row.learner.admissionNumber, row.required, row.paid, row.balance])];
    const blob = new Blob([rows.map(row => row.map(csvCell).join(",")).join("\n")], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "nexus-finance-ledger.csv"; link.click(); URL.revokeObjectURL(url);
  };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!learnerId || !amount || !reference.trim()) { toast.error("Select a learner and provide amount and receipt/reference"); return; } payment.mutate({ learnerId: Number(learnerId), amount: Number(amount), paymentMethod: method, reference: reference.trim() }); };
  const topBalances = useMemo(() => [...balances].sort((a, b) => b.balance - a.balance).slice(0, 8), [balances]);
  return <div className="page-enter space-y-6">
    <section className="flex flex-col gap-4 border-b border-[#dfdbd1] pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">Resources & finance</p><h1 className="mt-1 font-editorial text-[2rem] leading-none text-[#193d32]">One accountable school ledger.</h1><p className="mt-2 text-sm text-[#69796f]">Live fees, payments, expenditures and store balances from the existing NEXUS database.</p></div><div className="flex gap-2"><button onClick={exportLedger} className="quiet-button"><Download size={15}/>Download ledger</button><button onClick={() => window.print()} className="action-button"><Printer size={15}/>Print</button></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Collected" value={money(summary.data?.collected ?? overview.data?.totals.paid ?? 0)} icon={CircleDollarSign}/><Metric label="Expenditure" value={money(summary.data?.expenditure ?? 0)} icon={ReceiptText}/><Metric label="Net balance" value={money(summary.data?.balance ?? 0)} icon={WalletCards}/><Metric label="Low-stock items" value={String(lowStock.length)} icon={Package}/></section>
    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><form onSubmit={submit} className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Fee collection</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Receive and reconcile payment</h2><p className="mt-2 text-xs leading-5 text-[#718077]">Payments are written to the existing learner-linked ledger and audited with their receipt/reference.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-[#53675d] sm:col-span-2">Learner<select value={learnerId} onChange={e => setLearnerId(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"><option value="">Select learner</option>{learners.data?.map(row => <option key={row.id} value={row.id}>{row.fullName} · {row.admissionNumber}</option>)}</select></label><label className="text-xs font-bold text-[#53675d]">Amount (KES)<input type="number" min="1" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"/></label><label className="text-xs font-bold text-[#53675d]">Method<select value={method} onChange={e => setMethod(e.target.value as typeof method)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5"><option value="mpesa">M-Pesa</option><option value="bank">Bank</option><option value="cash">Cash</option></select></label><label className="text-xs font-bold text-[#53675d] sm:col-span-2">Receipt / transaction reference<input value={reference} onChange={e => setReference(e.target.value)} className="mt-2 w-full rounded-lg border border-[#d8ded7] bg-[#fbfaf5] px-3 py-2.5" placeholder="e.g. QWE12345"/></label></div><button disabled={payment.isPending} className="action-button mt-5">{payment.isPending ? "Posting…" : "Post payment"}</button></form><article className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Resource control</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Store watchlist</h2><div className="mt-4 space-y-2">{lowStock.length ? lowStock.map(item => <div key={item.id} className="flex items-center justify-between rounded-lg bg-[#fbf5e5] px-3 py-3 text-xs"><span className="font-bold text-[#73551e]">{item.name}</span><span className="font-mono text-[#9a6c19]">{item.quantity} {item.unit} left</span></div>) : <p className="rounded-lg bg-[#e7f0e7] p-3 text-xs text-[#315c4c]">No items are below their configured reorder level.</p>}</div></article></section>
    <section className="soft-card overflow-hidden rounded-[1.15rem]"><div className="flex items-center justify-between border-b border-[#e7e2d7] p-5"><div><p className="eyebrow">Learner balances</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">Outstanding accounts</h2></div><span className="rounded-full bg-[#e7f0e7] px-3 py-1 text-xs font-bold text-[#1d6a57]">{balances.length} learners</span></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-[#edf2ed] text-[.62rem] uppercase tracking-wider text-[#53675d]"><tr><th className="p-3">Learner</th><th className="p-3">Required</th><th className="p-3">Paid</th><th className="p-3">Balance</th></tr></thead><tbody>{topBalances.map(row => <tr key={row.learner.id} className="border-t border-[#eee9df]"><td className="p-3 font-bold text-[#28483f]">{row.learner.fullName}<span className="ml-2 font-normal text-[#718077]">{row.learner.admissionNumber}</span></td><td className="p-3">{money(row.required)}</td><td className="p-3 text-[#1d6a57]">{money(row.paid)}</td><td className={`p-3 font-bold ${row.balance > 0 ? "text-[#9c4038]" : "text-[#1d6a57]"}`}>{money(row.balance)}</td></tr>)}</tbody></table>{!topBalances.length && <p className="p-8 text-center text-sm text-[#718077]">No learner finance records are currently available.</p>}</div></section><section className="soft-card rounded-[1.15rem] p-5"><p className="eyebrow">Expenditure trail</p><div className="mt-3 grid gap-2 md:grid-cols-2">{(expenditures.data ?? []).slice(0, 8).map(row => <div key={row.id} className="flex items-start justify-between rounded-lg border border-[#eee9df] p-3 text-xs"><div><b className="text-[#28483f]">{row.category}</b><p className="mt-1 text-[#718077]">{row.description}</p></div><b className="text-[#9c4038]">{money(Number(row.amount))}</b></div>)}</div></section>
  </div>;
}
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof CircleDollarSign }) { return <article className="soft-card rounded-[1.1rem] p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#637067]">{label}</span><span className="rounded-lg bg-[#e5f1e8] p-2 text-[#1d6a57]"><Icon size={16}/></span></div><p className="mt-5 text-xl font-bold text-[#19342e]">{value}</p></article>; }
