import { useState } from "react";
import { MapPin, LocateFixed } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export function SchoolLocationSetup() {
  const utils = trpc.useUtils(); const setup = trpc.smis.clocking.status.useQuery();
  const [latitude, setLatitude] = useState(""); const [longitude, setLongitude] = useState(""); const [radius, setRadius] = useState("150");
  const save = trpc.smis.clocking.saveLocation.useMutation({ onSuccess: () => { toast.success("School coordinates saved"); void utils.smis.clocking.status.invalidate(); }, onError: e => toast.error(e.message.replaceAll("_", " ")) });
  const capture = () => { if (!navigator.geolocation) return toast.error("Location services are unavailable"); navigator.geolocation.getCurrentPosition(p => { setLatitude(p.coords.latitude.toFixed(7)); setLongitude(p.coords.longitude.toFixed(7)); toast.success("Current school location captured"); }, () => toast.error("Allow location access to capture coordinates"), { enableHighAccuracy: true, timeout: 10000 }); };
  return <section className="soft-card mb-5 min-w-0 rounded-[1.1rem] p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">Clocking in setup</p><h2 className="mt-1 text-lg font-bold text-[#28483f]">School location and allowed radius</h2><p className="mt-1 text-xs leading-5 text-[#718077]">Staff can clock in once per day only when their device is within this radius. Coordinates are never accepted from the browser without this server-side check.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${setup.data?.configured ? "bg-[#e5f1e8] text-[#1d6a57]" : "bg-[#f9efd8] text-[#9a6c19]"}`}>{setup.data?.configured ? "Configured" : "Not configured"}</span></div><div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold text-[#718077]">Latitude<input value={latitude || String(setup.data?.latitude ?? "")} onChange={e => setLatitude(e.target.value)} className="mt-1 w-full rounded-lg border border-[#d8ddd4] bg-[#fffefa] px-3 py-2 text-sm" placeholder="-0.1234567" /></label><label className="text-xs font-bold text-[#718077]">Longitude<input value={longitude || String(setup.data?.longitude ?? "")} onChange={e => setLongitude(e.target.value)} className="mt-1 w-full rounded-lg border border-[#d8ddd4] bg-[#fffefa] px-3 py-2 text-sm" placeholder="34.1234567" /></label><label className="text-xs font-bold text-[#718077]">Radius in metres<input type="number" min="25" max="1000" value={radius || String(setup.data?.radiusMeters ?? 150)} onChange={e => setRadius(e.target.value)} className="mt-1 w-full rounded-lg border border-[#d8ddd4] bg-[#fffefa] px-3 py-2 text-sm" /></label><div className="flex items-end gap-2"><button type="button" className="quiet-button" onClick={capture}><LocateFixed size={14} />Capture</button><button type="button" className="action-button" disabled={save.isPending} onClick={() => save.mutate({ latitude: Number(latitude || setup.data?.latitude), longitude: Number(longitude || setup.data?.longitude), radiusMeters: Number(radius || setup.data?.radiusMeters || 150) })}><MapPin size={14} />Save</button></div></div></section>;
}
